/**
 * Interface discovery — consumer side (work doc #17, mirrors the consumer half
 * of `RNS/Discovery.py`).
 *
 * Covers: aspect name-hash filtering, the LXMF stamp round-trip at discovery's
 * cheap work factor, msgpack `info`-dict parsing field-for-field against a
 * fixture generated by the Python reference, the generated `config_entry`
 * string, persistence via a KV storage adapter, the EventTarget surface, and
 * the freshness/authorization logic in `listDiscoveredInterfaces`.
 */
import assert from "node:assert";
import fs from "node:fs";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { Destination } from "../../src/core/destination.js";
import { Identity } from "../../src/core/identity.js";
import { DestType, Packet, PacketType } from "../../src/core/packet.js";
import {
  ACCEPTED_INTERFACE_TYPES,
  ASPECT,
  aspectNameHash,
  buildConfigEntry,
  buildDiscoveryAppData,
  DEFAULT_STAMP_VALUE,
  DISCOVERABLE_TYPES,
  FLAG_ENCRYPTED,
  generateDiscoveryStamp,
  InterfaceDiscovery,
  isHostname,
  isIpAddress,
  parseDiscoveryAnnounce,
  sanitizeName,
  WORKBLOCK_EXPAND_ROUNDS,
} from "../../src/transport/discovery.js";
import { TransportCore } from "../../src/transport/transport.js";
import { fromHex, toHex } from "../../src/utils/encoding.js";
import { MicroMsgPack } from "../../src/utils/msgpack.js";

const here = fileURLToPath(new URL(".", import.meta.url));
const FIXTURE_PATH = `${here}../fixtures/discovery_tcp.json`;

/** Reads the Python-generated TCP discovery fixture. */
function loadFixture() {
  return JSON.parse(fs.readFileSync(FIXTURE_PATH, "utf8"));
}

/**
 * Builds a complete discovery `info` Map (integer keys, matching Python's wire
 * format) with the optional geo fields defaulted to `nil`, the way Python's
 * `InterfaceAnnouncer.get_interface_announce_data` always emits them.
 * @param {Object} p
 * @returns {Map<number, any>}
 */
function makeInfo({
  type = "TCPServerInterface",
  transport = true,
  transportId,
  name,
  reachableOn,
  port,
  latitude = null,
  longitude = null,
  height = null,
}) {
  return new Map([
    [0x00, type],
    [0x01, transport],
    [0xfe, transportId],
    [0xff, name],
    [0x03, latitude],
    [0x04, longitude],
    [0x05, height],
    [0x02, reachableOn],
    [0x06, port],
  ]);
}

/** In-memory KV storage adapter implementing the work-doc-#16 interface. */
class MemoryStorage {
  constructor() {
    /** @type {Map<string, Map<string, Uint8Array>>} */
    this.namespaces = new Map();
  }
  /** @param {string} ns */
  #ns(ns) {
    let m = this.namespaces.get(ns);
    if (!m) {
      m = new Map();
      this.namespaces.set(ns, m);
    }
    return m;
  }
  async loadKey() {
    return null;
  }
  async saveKey() {}
  async get(ns, key) {
    return this.#ns(ns).get(key) ?? null;
  }
  async set(ns, key, value) {
    this.#ns(ns).set(key, value);
  }
  async delete(ns, key) {
    this.#ns(ns).delete(key);
  }
  async keys(ns) {
    return [...this.#ns(ns).keys()];
  }
}

// ---------------------------------------------------------------------
// Helper validators
// ---------------------------------------------------------------------

test("sanitizeName mirrors Python's sanitize_name", () => {
  assert.strictEqual(sanitizeName("Example Node"), "Example Node");
  assert.strictEqual(sanitizeName("  Leading"), "Leading");
  // Non-ASCII stripped, multi-space collapse.
  assert.strictEqual(sanitizeName("Hello   World"), "Hello World");
  assert.strictEqual(sanitizeName("Hello     World"), "Hello World");
  // Leading/trailing punctuation trimmed (only alphanumerics survive at edges).
  assert.strictEqual(sanitizeName("!!!Node!!!"), "Node");
  // Closing ")" is allowed at the trailing edge.
  assert.strictEqual(sanitizeName("Node (EU)"), "Node (EU)");
  assert.strictEqual(sanitizeName(null), null);
  assert.strictEqual(sanitizeName(""), null);
  assert.strictEqual(sanitizeName(undefined), null);
});

test("isIpAddress / isHostname port Python's ipaddress + hostname checks", () => {
  assert.ok(isIpAddress("127.0.0.1"));
  assert.ok(isIpAddress("8.8.8.8"));
  assert.ok(isIpAddress("::1"));
  assert.ok(isIpAddress("2001:db8::1"));
  assert.ok(isIpAddress("::"));
  assert.ok(!isIpAddress("999.1.1.1"));
  assert.ok(!isIpAddress("1.2.3"));
  assert.ok(!isIpAddress("not an ip"));

  assert.ok(isHostname("example.com"));
  assert.ok(isHostname("node.example.reticulum.network"));
  assert.ok(isHostname("a.b.c.d"));
  // Trailing all-numeric label looks like an IP, not a hostname.
  assert.ok(!isHostname("1.2.3.4"));
  assert.ok(!isHostname(""));
  assert.ok(!isHostname("a".repeat(300)));
});

// ---------------------------------------------------------------------
// Stamp round-trip + app_data assembly (producer primitives)
// ---------------------------------------------------------------------

test("a discovery stamp validates at the required cost and is rejected when tampered", async () => {
  const transportId = crypto.getRandomValues(new Uint8Array(16));
  const info = makeInfo({
    transportId,
    name: "Test Node",
    reachableOn: "example.com",
    port: 42424,
  });

  // generateDiscoveryStamp alone proves the producer path mints a stamp that
  // meets the required cost (separate random search from buildDiscoveryAppData).
  const [, genValue] = /** @type {[Uint8Array, number]} */ (
    await generateDiscoveryStamp(info, 8, WORKBLOCK_EXPAND_ROUNDS)
  );
  assert.ok(genValue >= 8, `achieved value ${genValue} should meet cost 8`);

  // Build the full app_data once and derive every assertion from it, so the
  // stamp the parser sees is the same one baked into the blob.
  const appData = await buildDiscoveryAppData(info, { stampCost: 8 });
  // Layout: flags(1) || packed || stamp(32). flags == 0 (no encryption).
  assert.strictEqual(appData[0], 0);
  assert.strictEqual(appData.length, 1 + (appData.length - 1 - 32) + 32);

  // A fresh Identity to stand in for the announced identity.
  const announced = await Identity.generate();
  const parsed = await parseDiscoveryAnnounce(appData, announced, {
    requiredValue: 8,
  });
  assert.ok(parsed, "parser should accept a freshly minted stamp");
  assert.strictEqual(parsed?.name, "Test Node");
  assert.strictEqual(parsed?.type, "TCPServerInterface");
  assert.ok(
    /** @type {number} */ (parsed?.value) >= 8,
    `parsed value ${parsed?.value} should meet cost 8`,
  );

  // Tamper one stamp byte → the parser must reject it.
  const tampered = new Uint8Array(appData);
  tampered[tampered.length - 1] ^= 0xff;
  const rejected = await parseDiscoveryAnnounce(tampered, announced, {
    requiredValue: 8,
  });
  assert.strictEqual(rejected, null, "tampered stamp must be rejected");
});

test("parseDiscoveryAnnounce returns null for too-short app_data", async () => {
  const announced = await Identity.generate();
  // STAMP_SIZE + 1 = 33 bytes is the minimum; 5 bytes is well below.
  const short = new Uint8Array(5);
  assert.strictEqual(await parseDiscoveryAnnounce(short, announced), null);
});

test("parseDiscoveryAnnounce rejects an unauthorized discovery source", async () => {
  const transportId = crypto.getRandomValues(new Uint8Array(16));
  const info = makeInfo({
    transportId,
    name: "Auth Test",
    reachableOn: "example.com",
    port: 42424,
  });
  const appData = await buildDiscoveryAppData(info, { stampCost: 8 });
  const announced = await Identity.generate();

  // Allow-list contains a *different* identity hash → reject.
  const other = await Identity.generate();
  const parsed = await parseDiscoveryAnnounce(appData, announced, {
    requiredValue: 8,
    discoverySources: [other.identityHash],
  });
  assert.strictEqual(parsed, null);
});

// ---------------------------------------------------------------------
// Python interop: parse a fixture produced by RNS/Discovery.py
// ---------------------------------------------------------------------

test("parses a Python-generated discovery announce byte-for-byte (interop)", async () => {
  const fx = loadFixture();
  const appData = fromHex(fx.app_data_hex);
  const announced = await Identity.fromPublicKey(
    fromHex(fx.announced_identity_pub_hex),
  );
  // Sanity: our Identity reconstruction matches the Python identity hash.
  assert.strictEqual(
    toHex(announced.identityHash),
    fx.announced_identity_hash_hex,
  );

  const info = await parseDiscoveryAnnounce(appData, announced, {
    requiredValue: fx.required_value,
    hops: fx.parsed.hops,
  });
  assert.ok(info, "fixture stamp must validate");

  const expected = fx.parsed;
  assert.strictEqual(info?.type, expected.type);
  assert.strictEqual(info?.transport, expected.transport);
  assert.strictEqual(info?.name, expected.name);
  assert.strictEqual(info?.value, expected.value);
  assert.strictEqual(info?.transportIdHex, expected.transport_id);
  assert.strictEqual(info?.networkIdHex, expected.network_id);
  assert.strictEqual(info?.hops, expected.hops);
  assert.strictEqual(info?.latitude, expected.latitude);
  assert.strictEqual(info?.longitude, expected.longitude);
  assert.strictEqual(info?.height, expected.height);
  assert.strictEqual(info?.reachable_on, expected.reachable_on);
  assert.strictEqual(info?.port, expected.port);
  assert.strictEqual(info?.config_entry, expected.config_entry);
  // discovery_hash: Python emits 32 raw bytes; we emit the hex of the same.
  assert.strictEqual(
    info?.discoveryHashHex,
    expected.discovery_hash.__bytes_hex__,
  );
  // stamp: same 32 bytes.
  assert.strictEqual(
    toHex(/** @type {Uint8Array} */ (info?.stamp)),
    expected.stamp.__bytes_hex__,
  );
});

// ---------------------------------------------------------------------
// config_entry generation across interface types
// ---------------------------------------------------------------------

test("buildConfigEntry renders BackboneInterface entries (non-Windows receiver)", () => {
  const entry = buildConfigEntry(
    {
      type: "BackboneInterface",
      name: "N1",
      transportIdHex: "abcdef0123456789abcdef0123456789",
      ifacNetname: null,
      ifacNetkey: null,
      reachableOn: "1.2.3.4",
      port: 4950,
    },
    true,
  );
  assert.strictEqual(
    entry,
    "[[N1]]\n" +
      "  type = BackboneInterface\n" +
      "  enabled = yes\n" +
      "  remote = 1.2.3.4\n" +
      "  target_port = 4950\n" +
      "  transport_identity = abcdef0123456789abcdef0123456789",
  );
});

test("buildConfigEntry falls back to TCPClientInterface on a Windows receiver", () => {
  const entry = buildConfigEntry(
    {
      type: "TCPServerInterface",
      name: "N2",
      transportIdHex: "deadbeef",
      ifacNetname: null,
      ifacNetkey: null,
      reachableOn: "host.example",
      port: 1234,
    },
    false,
  );
  assert.ok(entry.includes("type = TCPClientInterface"));
  assert.ok(entry.includes("target_host = host.example"));
});

test("buildConfigEntry appends ifac network_name / passphrase when present", () => {
  const entry = buildConfigEntry(
    {
      type: "I2PInterface",
      name: "I2P",
      transportIdHex: "feedface",
      ifacNetname: "mynet",
      ifacNetkey: "secret",
      reachableOn: "b32.example.i2p",
    },
    true,
  );
  assert.ok(entry.includes("network_name = mynet"));
  assert.ok(entry.includes("passphrase = secret"));
  assert.ok(entry.includes("transport_identity = feedface"));
});

// ---------------------------------------------------------------------
// InterfaceDiscovery orchestrator: aspect filter, event, persistence
// ---------------------------------------------------------------------

/**
 * Synthesizes a transport `"announce"` event carrying a discovery app_data,
 * matching the detail shape TransportCore._handleAnnounce dispatches.
 *
 * @param {Object} parts
 * @param {Uint8Array} parts.appData
 * @param {Uint8Array} parts.nameHash Discovery aspect name-hash.
 * @param {Identity} parts.announcedIdentity
 * @param {Uint8Array} parts.destinationHash
 * @returns {CustomEvent}
 */
function discoveryAnnounceEvent(parts) {
  return new CustomEvent("announce", {
    detail: {
      destinationHash: parts.destinationHash,
      identity: parts.announcedIdentity,
      nameHash: parts.nameHash,
      appData: parts.appData,
      packet: /** @type {any} */ ({}),
    },
  });
}

test("InterfaceDiscovery filters to the discovery aspect and dispatches 'discovered'", async () => {
  const transport = new TransportCore();
  const discovery = new InterfaceDiscovery({
    transport,
    requiredValue: 8,
  });
  await discovery.start();

  const announced = await Identity.generate();
  const transportId = crypto.getRandomValues(new Uint8Array(16));
  const info = makeInfo({
    transportId,
    name: "Event Node",
    reachableOn: "event.example",
    port: 4242,
  });
  const appData = await buildDiscoveryAppData(info, { stampCost: 8 });
  const nameHash = await aspectNameHash(ASPECT);
  const destHash = crypto.getRandomValues(new Uint8Array(16));

  /** @type {any[]} */
  const events = [];
  discovery.addEventListener("discovered", (/** @type {CustomEvent} */ e) => {
    events.push(e.detail.info);
  });

  // Matching aspect → fires.
  transport.dispatchEvent(
    discoveryAnnounceEvent({
      appData,
      nameHash,
      announcedIdentity: announced,
      destinationHash: destHash,
    }),
  );
  // Non-matching aspect → must NOT fire.
  const otherHash = new Uint8Array(10).fill(0xaa);
  transport.dispatchEvent(
    discoveryAnnounceEvent({
      appData,
      nameHash: otherHash,
      announcedIdentity: announced,
      destinationHash: destHash,
    }),
  );

  // dispatchEvent is synchronous; processing is serialized on an internal
  // chain, so drain it before asserting.
  await /** @type {any} */ (discovery)._chain;

  assert.strictEqual(events.length, 1);
  assert.strictEqual(events[0].name, "Event Node");
  discovery.stop();
});

test("InterfaceDiscovery persists and re-hydrates discoveries across instances", async () => {
  const storage = new MemoryStorage();
  const transportId = crypto.getRandomValues(new Uint8Array(16));
  const info = makeInfo({
    transportId,
    name: "Persist Node",
    reachableOn: "persist.example",
    port: 7000,
  });
  const appData = await buildDiscoveryAppData(info, { stampCost: 8 });
  const nameHash = await aspectNameHash(ASPECT);
  const announced = await Identity.generate();
  const destHash = crypto.getRandomValues(new Uint8Array(16));

  // First instance: ingest one discovery with a shared storage adapter.
  const t1 = new TransportCore();
  const d1 = new InterfaceDiscovery({
    transport: t1,
    requiredValue: 8,
    storageAdapter: storage,
  });
  await d1.start();
  t1.dispatchEvent(
    discoveryAnnounceEvent({
      appData,
      nameHash,
      announcedIdentity: announced,
      destinationHash: destHash,
    }),
  );
  await /** @type {any} */ (d1)._chain;
  const before = await d1.listDiscoveredInterfaces();
  assert.strictEqual(before.length, 1);
  assert.strictEqual(before[0].heard_count, 0);
  d1.stop();

  // Second instance, same adapter: the discovery survives the "restart".
  const t2 = new TransportCore();
  const d2 = new InterfaceDiscovery({
    transport: t2,
    requiredValue: 8,
    storageAdapter: storage,
  });
  await d2.start();
  const after = await d2.listDiscoveredInterfaces();
  assert.strictEqual(after.length, 1);
  assert.strictEqual(after[0].name, "Persist Node");
  assert.strictEqual(after[0].discoveryHashHex, before[0].discoveryHashHex);
  d2.stop();
});

test("InterfaceDiscovery bumps heard_count on repeat announces of the same interface", async () => {
  const transport = new TransportCore();
  const discovery = new InterfaceDiscovery({
    transport,
    requiredValue: 8,
    storageAdapter: new MemoryStorage(),
  });
  await discovery.start();

  const announced = await Identity.generate();
  const transportId = crypto.getRandomValues(new Uint8Array(16));
  const info = makeInfo({
    transportId,
    name: "Repeat Node",
    reachableOn: "repeat.example",
    port: 8080,
  });
  // Same info → same stamp is reusable; build once, replay twice.
  const appData = await buildDiscoveryAppData(info, { stampCost: 8 });
  const nameHash = await aspectNameHash(ASPECT);
  const destHash = crypto.getRandomValues(new Uint8Array(16));

  for (let i = 0; i < 3; i++) {
    transport.dispatchEvent(
      discoveryAnnounceEvent({
        appData,
        nameHash,
        announcedIdentity: announced,
        destinationHash: destHash,
      }),
    );
  }
  // Processing is serialized on an internal chain; drain it before asserting.
  await /** @type {any} */ (discovery)._chain;

  const list = await discovery.listDiscoveredInterfaces();
  assert.strictEqual(list.length, 1);
  assert.strictEqual(list[0].heard_count, 2, "first hear=0, then +1 twice");
  discovery.stop();
});

test("listDiscoveredInterfaces filters and prunes stale records", async () => {
  const transport = new TransportCore();
  const discovery = new InterfaceDiscovery({
    transport,
    requiredValue: 8,
    storageAdapter: new MemoryStorage(),
  });
  await discovery.start();

  // Inject two records directly into the store via the public parser path:
  // one fresh transport interface, one ancient (forged last_heard).
  const buildInfo = async (name, isTransport, ageSeconds) => {
    const transportId = crypto.getRandomValues(new Uint8Array(16));
    const map = makeInfo({
      transportId,
      name,
      transport: isTransport,
      reachableOn: "filter.example",
      port: 9000,
    });
    const appData = await buildDiscoveryAppData(map, { stampCost: 8 });
    const announced = await Identity.generate();
    const info = /** @type {any} */ (
      await parseDiscoveryAnnounce(appData, announced, {
        requiredValue: 8,
        hops: 1,
      })
    );
    info.last_heard = Date.now() / 1000 - ageSeconds;
    info.discovered = info.last_heard;
    info.heard_count = 0;
    return info;
  };

  // Use the orchestrator's remember path by dispatching real announces, then
  // forge the second record's age through the storage-backed store.
  const fresh = await buildInfo("Fresh", true, 0);
  const stale = await buildInfo("Stale", true, 8 * 24 * 60 * 60); // > THRESHOLD_REMOVE

  // Reach into the internal store to plant forged-age records.
  /** @type {Map<string, any>} */
  const store = /** @type {any} */ (discovery)._store;
  store.set(fresh.discoveryHashHex, fresh);
  store.set(stale.discoveryHashHex, stale);

  const all = await discovery.listDiscoveredInterfaces();
  assert.strictEqual(all.length, 1, "stale record should be pruned");
  assert.strictEqual(all[0].name, "Fresh");
  assert.strictEqual(all[0].status, "available");

  const onlyTransport = await discovery.listDiscoveredInterfaces({
    onlyTransport: true,
  });
  assert.strictEqual(onlyTransport.length, 1);

  discovery.stop();
});
