/**
 * @file ifac.test.js
 * @description Tests for IFAC (Interface Authentication Code) derivation,
 *   sealing and verification, with golden values cross-checked against the
 *   Python reference (`RNS/Reticulum.py`, `RNS/Transport.py`).
 */

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  deriveIfac,
  hasIfacFlag,
  IFAC_MIN_SIZE,
  IFAC_SALT,
  open,
  seal,
} from "../../src/core/ifac.js";
import { fromHex } from "../../src/utils/encoding.js";

// --- Python reference constants (RNS.Reticulum) ---------------------------

assert.deepStrictEqual(
  [...IFAC_SALT],
  [
    ...fromHex(
      "adf54d882c9a9b80771eb4995d702d4a3e733391b2a0f53f416d9f907e55cff8",
    ),
  ],
  "IFAC_SALT must match RNS.Reticulum.IFAC_SALT",
);
assert.strictEqual(IFAC_MIN_SIZE, 1, "IFAC_MIN_SIZE must match RNS.Reticulum");

// --- Golden values generated by tools/ifac_golden.py (RNS 1.4.2) ----------
const NETNAME = "test-network";
const NETKEY = "correct horse battery staple";
const GOLDEN_KEY =
  "23ab23f816803fdf35804470c4c3dad293b6a03b9d20cb250891e5f3d0909d715733033d48b6293f05991f17dd2d1113b143a83e9865fd9c93912cc2e17890f3";
const GOLDEN_SIG =
  "7dae8638baf2269abad8775bf42cd689f7cb01e4223c87326c1038a181aeed1e4b718b0ffea6e326788a08ec8b94196f74e07b3c96e34b41f0197d32da89470b";
const GOLDEN_KEY_NAME_ONLY =
  "51415420593053a0e9b1074ac1f2cf8e21a71055fc79a01878fba14c7d43e150f1e1c5869ecad2b0b814afcd73ec70ff12d96b1b98d3a60041d015f4c885d068";
const GOLDEN_KEY_KEY_ONLY =
  "6fc788958e9c2a0b221fb627610bee507b28454c1471f04f981b20fe7895550093f7ecbd17298a8f3a6ba92e1b28bceca33f941bcd0f32eb2a06a56fbc98cb57";

// Seal golden values (ifacSize = 8, raw below).
const GOLDEN_RAW = "0000000102030405060708090a0b0c0d0e0f00aabbccddee";
const GOLDEN_SEALED =
  "b24513b1000bf616fb038dce80f8a250f5ec3bff643d00b6f26e226a196bd735";

test("deriveIfac reproduces the Python reference ifac_key + signature", async () => {
  const m = await deriveIfac(NETNAME, NETKEY);
  assert.ok(m, "deriveIfac must return material for netname+netkey");
  assert.strictEqual(
    Buffer.from(m.ifacKey).toString("hex"),
    GOLDEN_KEY,
    "ifac_key must match RNS",
  );
  assert.strictEqual(
    Buffer.from(m.ifacSignature).toString("hex"),
    GOLDEN_SIG,
    "ifac_signature must match RNS",
  );
});

test("deriveIfac works with netname only", async () => {
  const m = await deriveIfac(NETNAME, null);
  assert.strictEqual(
    Buffer.from(m.ifacKey).toString("hex"),
    GOLDEN_KEY_NAME_ONLY,
  );
});

test("deriveIfac works with passphrase only", async () => {
  const m = await deriveIfac(null, NETKEY);
  assert.strictEqual(
    Buffer.from(m.ifacKey).toString("hex"),
    GOLDEN_KEY_KEY_ONLY,
  );
});

test("deriveIfac returns null when no secret is provided", async () => {
  assert.strictEqual(await deriveIfac(null, null), null);
  assert.strictEqual(await deriveIfac("", ""), null);
  assert.strictEqual(await deriveIfac(undefined, undefined), null);
});

test("seal reproduces the Python reference sealed bytes", async () => {
  const m = await deriveIfac(NETNAME, NETKEY);
  const cfg = { ifacIdentity: m.ifacIdentity, ifacKey: m.ifacKey, ifacSize: 8 };
  const raw = fromHex(GOLDEN_RAW);
  const sealed = await seal(raw, cfg);
  assert.strictEqual(
    Buffer.from(sealed).toString("hex"),
    GOLDEN_SEALED,
    "sealed output must match RNS Transport.transmit byte-for-byte",
  );
  assert.ok(hasIfacFlag(sealed), "sealed packet must have the IFAC flag set");
});

test("open reverses seal and recovers the original bytes", async () => {
  const m = await deriveIfac(NETNAME, NETKEY);
  const cfg = { ifacIdentity: m.ifacIdentity, ifacKey: m.ifacKey, ifacSize: 8 };
  const sealed = fromHex(GOLDEN_SEALED);
  const opened = await open(sealed, cfg);
  assert.ok(opened, "open must succeed on a valid sealed packet");
  assert.strictEqual(
    Buffer.from(opened).toString("hex"),
    GOLDEN_RAW,
    "open must recover the original unsealed bytes",
  );
  assert.ok(!hasIfacFlag(opened), "opened packet must have the flag cleared");
});

test("seal/open round-trips a freshly serialized packet at various ifacSizes", async () => {
  const { Packet, PacketType, DestType } = await import(
    "../../src/core/packet.js"
  );
  const m = await deriveIfac(NETNAME, NETKEY);
  const packet = new Packet({
    packetType: PacketType.DATA,
    destinationType: DestType.SINGLE,
    destinationHash: fromHex("0102030405060708090a0b0c0d0e0f10"),
    payload: new TextEncoder().encode("hello ifac"),
  });
  const raw = packet.serialize();

  for (const ifacSize of [1, 8, 16, 32, 64]) {
    const cfg = {
      ifacIdentity: m.ifacIdentity,
      ifacKey: m.ifacKey,
      ifacSize,
    };
    const sealed = await seal(raw, cfg);
    const opened = await open(sealed, cfg);
    assert.ok(opened, `open failed at ifacSize=${ifacSize}`);
    assert.deepStrictEqual(
      [...opened],
      [...raw],
      `round-trip mismatch at ifacSize=${ifacSize}`,
    );
  }
});

test("open returns null on a mismatched key (silent drop)", async () => {
  const m1 = await deriveIfac(NETNAME, NETKEY);
  const m2 = await deriveIfac("other-network", "wrong passphrase");
  const cfg1 = {
    ifacIdentity: m1.ifacIdentity,
    ifacKey: m1.ifacKey,
    ifacSize: 8,
  };
  const cfg2 = {
    ifacIdentity: m2.ifacIdentity,
    ifacKey: m2.ifacKey,
    ifacSize: 8,
  };
  const sealed = await seal(fromHex(GOLDEN_RAW), cfg1);
  const opened = await open(sealed, cfg2);
  assert.strictEqual(opened, null, "mismatched key must drop the packet");
});

test("open returns null on a truncated packet", async () => {
  const m = await deriveIfac(NETNAME, NETKEY);
  const cfg = { ifacIdentity: m.ifacIdentity, ifacKey: m.ifacKey, ifacSize: 8 };
  // Too short to contain header + IFAC.
  assert.strictEqual(
    await open(new Uint8Array([0x80, 0x00, 0x01, 0x02]), cfg),
    null,
  );
});

test("seal preserves the IFAC flag through the mask on byte 0", async () => {
  const m = await deriveIfac(NETNAME, NETKEY);
  const cfg = { ifacIdentity: m.ifacIdentity, ifacKey: m.ifacKey, ifacSize: 8 };
  const sealed = await seal(fromHex(GOLDEN_RAW), cfg);
  assert.strictEqual(sealed[0] & 0x80, 0x80, "bit 7 must survive masking");
});
