/**
 * LXMF propagation data layer — interop with the Python reference.
 *
 * Verifies (against `test/fixtures/lxmf_propagation.json`, generated by the
 * Python LXMF reference) the three byte-exact pieces of the propagation
 * protocol (§5.3 / §5.9.5):
 *
 *   - propagation-node announce app_data (buildPropagationNodeAppData)
 *   - transient_id = SHA-256(lxmf_data)
 *   - the propagation submit container msgpack([time, [lxmf_data...]])
 *
 * plus bidirectional crypto interop:
 *   - Python → JS: decrypt & unpack a Python-packed lxmf_data
 *   - JS → Python: a JS-packed lxmf_data decrypts & unpacks under Python
 *     (scripts/verify_propagation_decrypt.py), proving a Python propagation
 *     node can ingest JS-originated messages.
 */
import assert from "node:assert";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, test } from "node:test";
import { Destination } from "../../src/core/destination.js";
import { Identity } from "../../src/core/identity.js";
import { DestType } from "../../src/core/packet.js";
import {
  buildPropagationNodeAppData,
  parsePropagationNodeAppData,
} from "../../src/lxmf/announce_data.js";
import { Message } from "../../src/lxmf/message.js";
import {
  packPropagationContainer,
  unpackPropagationContainer,
} from "../../src/lxmf/propagation.js";
import { fromHex, toHex } from "../../src/utils/encoding.js";

const FIXTURE = JSON.parse(
  readFileSync(
    join(import.meta.dirname, "..", "fixtures", "lxmf_propagation.json"),
    "utf8",
  ),
);

/** Python verifier for the JS→Python direction; skipped if unavailable. */
function pythonAvailable() {
  try {
    execFileSync(
      "python3",
      [
        "-c",
        "import sys; sys.path.insert(0,'Reticulum'); import RNS, LXMF, umsgpack",
      ],
      { stdio: "ignore" },
    );
    return true;
  } catch {
    return false;
  }
}

describe("propagation-node announce app_data (§5.9.5) — byte-exact vs Python", () => {
  test("buildPropagationNodeAppData reproduces the Python bytes", () => {
    const { inputs, expected } = FIXTURE.appData;
    const got = buildPropagationNodeAppData({
      timebase: inputs.timebase,
      nodeState: inputs.nodeState,
      perTransferLimitKb: inputs.perTransferLimitKb,
      perSyncLimitKb: inputs.perSyncLimitKb,
      stampCost: inputs.stampCost,
      stampCostFlexibility: inputs.stampCostFlex,
      peeringCost: inputs.peeringCost,
      name: inputs.name,
    });
    assert.strictEqual(toHex(got), expected);
  });

  test("parse round-trips the Python bytes", () => {
    const parsed = parsePropagationNodeAppData(
      fromHex(FIXTURE.appData.expected),
    );
    assert.ok(parsed);
    const i = FIXTURE.appData.inputs;
    assert.strictEqual(parsed.nodeState, i.nodeState);
    assert.strictEqual(parsed.perTransferLimitKb, i.perTransferLimitKb);
    assert.strictEqual(parsed.perSyncLimitKb, i.perSyncLimitKb);
    assert.strictEqual(parsed.stampCost, i.stampCost);
    assert.strictEqual(parsed.stampCostFlexibility, i.stampCostFlex);
    assert.strictEqual(parsed.peeringCost, i.peeringCost);
    assert.strictEqual(parsed.name, i.name);
    assert.strictEqual(parsed.timebase, i.timebase);
  });

  test("parse tolerates missing/empty app_data", () => {
    assert.strictEqual(parsePropagationNodeAppData(null), null);
    assert.strictEqual(parsePropagationNodeAppData(new Uint8Array(0)), null);
  });
});

describe("propagation transient_id + container (§5.3) — byte-exact vs Python", () => {
  const py = FIXTURE.pythonPropagation;

  test("transientIdFromPropagationData == SHA-256(lxmf_data) == Python", async () => {
    const lxmfData = fromHex(py.lxmfData);
    const transientId = await Message.transientIdFromPropagationData(lxmfData);
    assert.strictEqual(toHex(transientId), py.transientId);
  });

  test("unpackPropagationContainer recovers [sendTime, [lxmf_data]]", () => {
    const container = unpackPropagationContainer(fromHex(py.container));
    assert.ok(container);
    assert.strictEqual(container.messages.length, 1);
    assert.strictEqual(toHex(container.messages[0]), py.lxmfData);
  });

  test("packPropagationContainer round-trips", () => {
    const lxmfData = fromHex(py.lxmfData);
    const packed = packPropagationContainer([lxmfData], py.sendTime);
    const back = unpackPropagationContainer(packed);
    assert.ok(back);
    assert.strictEqual(back.sendTime, py.sendTime);
    assert.strictEqual(toHex(back.messages[0]), py.lxmfData);
  });
});

describe("Python → JS propagation decrypt interop", () => {
  const py = FIXTURE.pythonPropagation;

  test("fromPropagationData decrypts & unpacks a Python-packed message", async () => {
    const recipient = await Identity.fromBytes(
      fromHex(FIXTURE.recipientIdentity128),
    );
    const dest = await Destination.IN(
      "lxmf.delivery",
      DestType.SINGLE,
      recipient,
      null,
    );
    // Destination hash matches the Python fixture.
    assert.strictEqual(
      toHex(dest.destinationHash),
      FIXTURE.recipientDestinationHash,
    );

    const msg = await Message.fromPropagationData(fromHex(py.lxmfData), dest);
    assert.ok(msg, "decryption should succeed");
    assert.strictEqual(msg.title, FIXTURE.message.title);
    assert.strictEqual(msg.content, FIXTURE.message.content);

    // Signature validates against the source identity.
    const source = await Identity.fromBytes(fromHex(FIXTURE.sourceIdentity128));
    assert.ok(await msg.verifySignature(source));
  });

  test("fromPropagationData rejects an undecryptable blob (wrong recipient)", async () => {
    const other = await Identity.generate();
    const dest = await Destination.IN(
      "lxmf.delivery",
      DestType.SINGLE,
      other,
      null,
    );
    const msg = await Message.fromPropagationData(fromHex(py.lxmfData), dest);
    assert.strictEqual(msg, null);
  });
});

describe("JS propagation round-trip (pack → unpack)", () => {
  test("toPropagationData → fromPropagationData recovers the message", async () => {
    const recipient = await Identity.fromBytes(
      fromHex(FIXTURE.recipientIdentity128),
    );
    const source = await Identity.fromBytes(fromHex(FIXTURE.sourceIdentity128));
    const outDest = await Destination.OUT(
      "lxmf.delivery",
      DestType.SINGLE,
      recipient,
      null,
    );
    const inDest = await Destination.IN(
      "lxmf.delivery",
      DestType.SINGLE,
      recipient,
      null,
    );

    const msg = new Message({
      destinationHash: outDest.destinationHash,
      sourceHash: (
        await Destination.OUT("lxmf.delivery", DestType.SINGLE, source, null)
      ).destinationHash,
      timestamp: 1715000000,
      title: "JS Round Trip",
      content: "packed and unpacked in JS",
    });
    const { lxmfData, transientId } = await msg.toPropagationData(
      source,
      outDest,
    );

    // lxmf_data = dest_hash(16) + encrypted(src(16)+sig(64)+payload); transient_id = SHA-256(lxmf_data)
    assert.ok(
      lxmfData.length > 16 + 16 + 64,
      "lxmf_data must carry dest+src+sig at minimum",
    );
    assert.strictEqual(transientId.length, 32);
    assert.deepStrictEqual(
      transientId,
      await Message.transientIdFromPropagationData(lxmfData),
    );

    const recovered = await Message.fromPropagationData(lxmfData, inDest);
    assert.ok(recovered);
    assert.strictEqual(recovered.title, "JS Round Trip");
    assert.strictEqual(recovered.content, "packed and unpacked in JS");
    assert.ok(await recovered.verifySignature(source));
  });
});

describe("JS → Python propagation decrypt interop", () => {
  test("a JS-packed lxmf_data decrypts & unpacks under the Python reference", async () => {
    if (!pythonAvailable()) {
      console.warn("python3/RNS not available — skipping JS→Python interop");
      return;
    }
    const recipient = await Identity.fromBytes(
      fromHex(FIXTURE.recipientIdentity128),
    );
    const source = await Identity.fromBytes(fromHex(FIXTURE.sourceIdentity128));
    const outDest = await Destination.OUT(
      "lxmf.delivery",
      DestType.SINGLE,
      recipient,
      null,
    );
    const srcOut = await Destination.OUT(
      "lxmf.delivery",
      DestType.SINGLE,
      source,
      null,
    );

    const msg = new Message({
      destinationHash: outDest.destinationHash,
      sourceHash: srcOut.destinationHash,
      timestamp: 1720000000,
      title: "From JS",
      content: "Python must decrypt this",
    });
    const { lxmfData } = await msg.toPropagationData(source, outDest);

    const outJson = join(
      tmpdir(),
      `lxmf-verify-${process.pid}-${Date.now()}.json`,
    );
    execFileSync("python3", [
      join(
        import.meta.dirname,
        "..",
        "..",
        "scripts",
        "verify_propagation_decrypt.py",
      ),
      FIXTURE.recipientIdentity128,
      toHex(lxmfData),
      outJson,
    ]);
    const res = JSON.parse(readFileSync(outJson, "utf8"));
    assert.strictEqual(res.ok, true);
    assert.strictEqual(res.title, "From JS");
    assert.strictEqual(res.content, "Python must decrypt this");
  });
});
